name: Front-end-ci
on: [push]

jobs:
  ci:
    name: Unit and end-to-end tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-ui
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Unit Tests
        run: npm test -- --watchAll=false  --passWithNoTests

      - name: E2E Tests
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: "http://localhost:3000"
